export const cssSection = "w-full"
export const cssArticle = "mx-auto w-10/12 py-5 rounded-md"
export const cssBtn = "py-1 px-4 rounded-full transform hover:scale-110 font-bold duration-300 hover:grayscale"
export const cssBtnSucess = `${cssBtn} bg-purple-500 text-white`
export const cssBtnDanger = `${cssBtn} bg-red-500 text-white`
export const cssBtnSecondary = `${cssBtn} bg-gray-500 text-white`
export const cssTitle = "text-2xl font-bold"
export const cssSubTitle = "text-xl font-bold"
export const cssInput = "py-1 px-3 rounded-md bg-purple-300 placeholder-purple-800"
export const cssCard = "bg-slate-900 p-5 rounded-md transform hover:scale-110 duration-300 hover:bg-slate-700"
export const cssGrid = "grid grid-cols-3 gap-10"
export const cssModal = "absolute bg-purple-500/80 z-10 flex items-center justify-center min-h-screen w-full"